behaviors:
  SoccerTwos:
    trainer_type: ppo
    hyperparameters:
      batch_size: 4096
      buffer_size: 20480
      learning_rate: 0.00025
      beta: 0.01
      epsilon: 0.2
      lambd: 0.97
      num_epoch: 5
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 3000000
    time_horizon: 500
    summary_freq: 10000
    threaded: true
    keep_checkpoints: 5
    checkpoint_interval: 200000
    self_play:
      save_steps: 20000
      window: 15
      play_against_current_self: 0.5
      team_change: 0.5
      initial_elo: 1200.0
